### ISSUE TITLE
Docs for `find_chrome()` should include advice on changing default chrome browser

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/chromote#104]
It'd be helpful to include a description of both how Chrome is found by default and how users can instruct chromote to use an alternative browser. This may be documented elsewhere in chromote, but a quick search on the pkgdown site didn't turn anything up.

We could then link to this documentation from other places, e.g. https://github.com/rstudio/webshot2/issues/49.

**Comment by stla** [comment]
related: https://github.com/rstudio/chromote/issues/108

**Comment by gadenbuie** [comment]
This was completed in #118
