### ISSUE TITLE
Possibility to use a portable version

### ISSUE THREAD

**Issue by Waschoi** [rstudio/chromote#105]
Hi and many thanks for all your work!

I have limited options here at work to have Chrome installed. Is it possible to use the package also with the portable version. 
I have already set Sys.setenv("CHROMOTE_CHROME" = "C:/Portable Software/Chrome/GoogleChromePortable/GoogleChromePortable.exe"), but the following error appears:
Error in launch_chrome(path, args) : 
  Chrome debugging port not open after 10 seconds.

Best

Martin

**Comment by hadley** [comment]
Thanks for the suggestion @stla!
