### ISSUE TITLE
`find_chrome` on Windows is not informative when it fails

### ISSUE THREAD

**Issue by stla** [rstudio/chromote#108]
Hello,

```r
> chromote::find_chrome()
Error trying to find path to Chrome
NULL
```

It would be nice to print a message similar to the one printed for Linux ("Try setting the CHROMOTE_CHROME environment variable or adding one of these executables to your PATH."). I had to look at the code to find `CHROMOTE_CHROME`.

**Comment by dmurdoch** [comment]
A related issue:  `find_chrome()` is documented to return a path, but it works if `CHROMOTE_CHROME` is set to a command like `chrome`, which will be executed successfully if it is on the `PATH`.  This came up in https://github.com/dmurdoch/rgl/issues/376 .  

I think it would be good if `find_chrome()` validated the result when it finds `CHROMOTE_CHROME`, either by `file.exists()` if it really is intended to be a path to the executable, or by `Sys.which()` if a command is acceptable.  In the latter case, the help page should be updated as well.
