### ISSUE TITLE
GitHub Actions not working on Windows

### ISSUE THREAD

**Issue by ashbythorpe** [rstudio/chromote#114]
I was having trouble getting GitHub Actions to work for a package I was working on that depends on chromote, so I created a smaller package to reproduce the problem:
https://github.com/ashbythorpe/chromotegha

This package is essentially a blank slate, with one test:
https://github.com/ashbythorpe/chromotegha/blob/master/tests/testthat/test-chromote.R
``` r
test_that("chromote works", {
  session <- chromote::ChromoteSession$new()
  session$close()
})
```

It also contains the result of `usethis::use_github_action("check-standard")` (https://github.com/r-lib/actions/blob/v2/examples/check-standard.yaml), which runs `R CMD CHECK` on Ubuntu, MacOS and Windows.
https://github.com/ashbythorpe/chromotegha/blob/master/.github/workflows/R-CMD-check.yaml

When this is pushed to GitHub, all tasks succeed except the one on Windows ("windows-latest (release)").
https://github.com/ashbythorpe/chromotegha/actions/runs/5617334802
https://github.com/ashbythorpe/chromotegha/actions/runs/5617334802/job/15221268178

This workflow fails because the single test fails, resulting in an error:
```
Error in `launch_chrome(path, args)`: Chrome debugging port not open after 10 seconds.
Backtrace:
    ▆
 1. └─chromote::ChromoteSession$new() at test-chromote.R:2:2
 2.   └─chromote (local) initialize(...)
 3.     └─chromote::default_chromote_object()
 4.       ├─chromote::set_default_chromote_object(Chromote$new())
 5.       └─Chromote$new()
 6.         └─chromote (local) initialize(...)
 7.           └─Chrome$new()
 8.             └─chromote (local) initialize(...)
 9.               └─chromote:::launch_chrome(path, args)
```

This is somewhat similar to #5.

**Comment by gadenbuie** [comment]
Thanks for the report @ashbythorpe and for the awesome reprex! I forked your repo and fiddled with it, but got no where. But just now I realized, thanks to a conversation with @schloerke, that we might just need to give Chrome more time to start up. I just today merged a PR to add a `chromote.timeout` option, and setting this to a higher value than `10` seconds worked. You can add a line like the following to `testthat.R`:

```r
options(chromote.timeout = 60)
```

Here's where I tried it: https://github.com/gadenbuie/test-chromotegha/commit/b4da48346c062e6c108a0d84bd90eaeb530c97f0

Please let me know if that works out for you (you'll also need to use the dev version of chromote, although this release should land on CRAN very soon).

**Comment by stla** [comment]
That's because you likely have an environment variable `HTTP(S)_PROXY`. See https://github.com/rstudio/chromote/issues/124.

**Comment by gadenbuie** [comment]
@stla I am not an expert on GitHub's Windows runners, but I'm fairly certain they do not set `HTTP_PROXY` by default. The examples in this issue use a standard GHA runner with no other customizations. Chrome is just slow to start on those runners.

**Comment by ashbythorpe** [comment]
@gadenbuie Thanks, it's working now.

**Comment by andrie** [comment]
I tried this advice and it works great.

I had to change the timeout to 120, as in the linked example.  60 seconds was just too short.

Many thanks, @gadenbuie
