### ISSUE TITLE
Fill html fields

### ISSUE THREAD

**Issue by sybrohee** [rstudio/chromote#125]
Dear all,

This looks like a stupid question but is it possible to enter values in form fields using chromote. That way, we could use it as e.g. Selenium or cypress.

Many thanks for your help,

Sylvain

**Comment by sybrohee** [comment]
shinytest2 is indeed a really nice tool I wanted to make it work on a shiny web application that is made available via [shinyproxy ](https://www.shinyproxy.io/) which seems impossible (I spent quite a few hours on that).

This is why I wanted   a bit more "high level" implementation of my tests  (login and / or different shiny text input fields) by using the library chromote which (if I understood correctly) is used by shinytest2.

I would be happy to hear about any insight you could give me.

Thank you for your really nice job with chromote.

Sylvain

**Comment by ashbythorpe** [comment]
Hi @sybrohee! I recently released a high-level wrapper for both chromote and RSelenium called [selenider](https://github.com/ashbythorpe/selenider), that you might find useful, if you are still looking to automate your website.

**Comment by sybrohee** [comment]
Hi @ashbythorpe. Interesting, I will have a look at it in the coming days. Thank you for telling me!

**Comment by hadley** [comment]
I'm closing this issue because chromote will remain a low level packages that other package build on top of to provide a user-friendly interface.
