### ISSUE TITLE
Click DOWNLOAD button via coordinates and save download-file using CHROMOTE

### ISSUE THREAD

**Issue by dendrit1** [rstudio/chromote#126]
Hello,

I use CHROMOTE-package to navigate to a web site 
(example: [https://www.clinicaltrialsregister.eu/ctr-search/search?query=asthma&status=completed&status=not-authorised&status=ongoing&status=prematurely-ended&status=prohibited-by-ca&status=restarted&status=suspended-by-ca&status=temporarily-halted&status=trial-now-transitioned&page=2](HERE) ) 
and to click via coordinates onto the download button, then I want to download the TXT-file.

For clicking the button I wrote the following R-code. 
**But how and where do I get the download TXT-file - which functions/code are needed??**

```
library(chromote)
set_chrome_args(c("--incognito","--disable-gpu","--force-color-profile=srgb","--disable-extensions","--mute-audio")) #--incognito means that nothing will be cached

b <- ChromoteSession$new(wait_ = TRUE) # "b" stands for "browser"
Sys.sleep(runif(1, 2, 3))

  b1 <- b$new_session(width = 1700, height = 1800, wait_ = TRUE) #wait_ = TRUE
  b1$Network$setUserAgentOverride(userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36") #define user-agent in order to avoid 403 error of certain webpages by simulating a "real" browser, not an automated headless browser
  
  b1$Page$navigate("https://www.clinicaltrialsregister.eu/ctr-search/search?query=asthma&status=completed&status=not-authorised&status=ongoing&status=prematurely-ended&status=prohibited-by-ca&status=restarted&status=suspended-by-ca&status=temporarily-halted&status=trial-now-transitioned&page=2", wait_ = TRUE) 
  Sys.sleep(runif(1, 3, 4))
  

  x = 1260 ## horizontal X coordinate of the button relative to the main frame's viewport in CSS pixels; 
  y = 1745 ## vertical Y coordinate of the buttonrelative to the main frame's viewport in CSS pixels. 0 refers to the top of the viewport and Y increases as it proceeds towards the bottom of the viewport;

  b1$Input$dispatchMouseEvent(type = "mousePressed", x = x, y = y, button="left", clickCount=1) # clickCount=Number of times the mouse button was clicked, 1= normal click, 2 = double-click
  b1$Input$dispatchMouseEvent(type = "mouseReleased", x = x, y = y, button="left", clickCount=1) # see: https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchMouseEvent
```

**Thanks in advance for your help!**

**Comment by wch** [comment]
I think you can use `b$Browser$setDownloadBehavior` to control how it handles downloads. See this:
https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setDownloadBehavior

**Comment by dendrit1** [comment]
@wch Winston Chang, thanks so much! It really works so easily (under Windows 10 Entrprise):

`  b$Browser$setDownloadBehavior(behavior = "allow", downloadPath = "C:\\Users\\userName\\temp_local\\EUR-CTR_tests\\")`

**Comment by wch** [comment]
Great, glad to hear that!
