### ISSUE TITLE
[docs] Add documentation for web scraping functions

### ISSUE THREAD

**Issue by jonekeat** [rstudio/chromote#127]
is it possible to use `chromote` to open an Chrome session interactively and perform web scraping like [RSelenium](https://docs.ropensci.org/RSelenium/index.html)?

I found that `chromote` is a lot easier to setup but very little documentation in web scraping, as compared to RSelenium, it will be very beneficial to the community that need to perform web automation

related to #47, https://github.com/rstudio/chromote/issues/59

**Comment by hadley** [comment]
I'm about to add those capabilities to rvest, so I'd suggest you try them out: https://github.com/tidyverse/rvest/pull/362.  chromote is very low-level.
