### ISSUE TITLE
Runtime$evaluate() via ChromeRemote not working

### ISSUE THREAD

**Issue by alandipert** [rstudio/chromote#15]
I'm on Ubuntu 18.04 with Chrome 79 and R 3.6.2.

First, I started Chrome from the shell like this:

     google-chrome --remote-debugging-port=9222 --user-data-dir=remote-profile

In RStudio, when I try `Runtime$evaluate()` it doesn't work:

```
> library(chromote)
> b <- ChromeRemote$new(host = "localhost", port = 9222)
> r <- Chromote$new(browser = b)
> x <- r$Runtime$evaluate("123")
Error in onRejected(reason) : code: -32601
  message: 'Runtime.evaluate' wasn't found
```

It _does_ work when I create a Chrome session via `ChromoteSession$new()`.

**Comment by alandipert** [comment]
Update: I asked @wch about this and he suggested I use `ChromoteSession$new()` instead of `Chromote$new()`. I will try this and report back.

**Comment by alandipert** [comment]
Woohoo, it worked when I did it like this:

```
> r <- Chromote$new(browser = ChromeRemote$new(host="localhost",port=9222))
> b <- ChromoteSession$new(parent = r)
> b$Runtime$evaluate("alert('foobar')")
```

**Comment by wch** [comment]
You could also do `r$new_session()`:

```R
r <- Chromote$new(browser = ChromeRemote$new(host="localhost",port=9222))
b <- r$new_session()
b$Runtime$evaluate("alert('foobar')")
```
