### ISSUE TITLE
Is it expected that a screenshot from an URL with fragment capture the page from the top?

### ISSUE THREAD

**Issue by maelle** [rstudio/chromote#167]
Thanks a lot for a very useful package.

In the reprex below I'd expect the screenshot to start where the fragment/anchor is which means at the `#unpaid-spare-time-efforts` section not at the top of the page. Is it the normal behavior or a bug?

``` r
library("chromote")
screen_width <- 1920
screen_height <- 1080
b <- ChromoteSession$new(height = screen_height, width = screen_width)
b$Page$navigate("https://ropensci.org/blog/2024/08/20/my-experience-with-long-term-maintenance-of-an-r-package/#unpaid-spare-time-efforts")
#> $frameId
#> [1] "F750C738A9A077E1F561ADEA6CF41FBC"
#> 
#> $loaderId
#> [1] "46D9A8EF3E35DDC1C5B7946C2949789C"
Sys.sleep(3)

# with default screenshot ----
temp_file <- withr::local_tempfile(fileext = ".png")
b$screenshot(temp_file, delay = 2)
#> [1] "/tmp/RtmpB3Xwjj/file1265d33932a3.png"
magick::image_read(temp_file)
```

<img src="https://i.imgur.com/kYz3zdK.png" width="1905" />

<sup>Created on 2024-08-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

My workaround is to use a cliprec after finding the coordinates of the anchor.

**Comment by wch** [comment]
The `$screenshot()` method captures the entire page, or a region specified by `cliprect`. I think it would be unexpected behavior if it captured starting from part way down the page, going to the bottom.

You might be able to use `selector` to screenshot just the region that you're interested in.

**Comment by maelle** [comment]
Thank you for clarifying!!
