### ISSUE TITLE
Are left and top of cliprect swapped?

### ISSUE THREAD

**Issue by maelle** [rstudio/chromote#168]
Compare

``` r
library("chromote")
screen_width <- 1920
screen_height <- 1080
b <- ChromoteSession$new(height = screen_height, width = screen_width)
b$Page$navigate("https://ropensci.org/blog/2024/08/20/my-experience-with-long-term-maintenance-of-an-r-package/#unpaid-spare-time-efforts")
#> $frameId
#> [1] "7B19DEA92DAEE2604FF79D5B39950B3F"
#> 
#> $loaderId
#> [1] "2B32CDC2E6F69E981ECB6199583C781F"
Sys.sleep(3)

# with default screenshot ----
temp_file <- withr::local_tempfile(fileext = ".png")
b$screenshot(temp_file, delay = 2,
  cliprect = c(top = 500, left = 0, width = screen_width, height = screen_height))
#> [1] "/tmp/RtmpeDq7yu/file127753c8bb97c.png"
magick::image_read(temp_file)
```

<img src="https://i.imgur.com/mt6W3G4.png" width="1920" />

<sup>Created on 2024-08-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

to

``` r
library("chromote")
screen_width <- 1920
screen_height <- 1080
b <- ChromoteSession$new(height = screen_height, width = screen_width)
b$Page$navigate("https://ropensci.org/blog/2024/08/20/my-experience-with-long-term-maintenance-of-an-r-package/#unpaid-spare-time-efforts")
#> $frameId
#> [1] "0A2C843D4682A15E246580F29EA7D888"
#> 
#> $loaderId
#> [1] "00A249C14C2D0A62758B12CE3489FB58"
Sys.sleep(3)

# with default screenshot ----
temp_file <- withr::local_tempfile(fileext = ".png")
b$screenshot(temp_file, delay = 2,
  cliprect = c(top = 0, left = 500, width = screen_width, height = screen_height))
#> [1] "/tmp/RtmpeKWSkN/file1283f5794fdf8.png"
magick::image_read(temp_file)
```

<img src="https://i.imgur.com/asVgcBl.png" width="1920" />

<sup>Created on 2024-08-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by wch** [comment]
The `cliprect` parameter takes a (unnamed) vector/list with left, top, width and height:

https://github.com/rstudio/chromote/blob/b093ba6640fde46a9ec31e7d2b7103dc8952878f/R/screenshot.R#L28-L30

If you give it a named vector, those names will be ignored; only the order matters.


However, I can see that the documentation is incorrect, as it implies that it wants a named list with `x`, `y`, `width`, and `height`, which is not quite the same.

https://github.com/rstudio/chromote/blob/b093ba6640fde46a9ec31e7d2b7103dc8952878f/R/chromote_session.R#L294

**Comment by maelle** [comment]
Thank you!!
