### ISSUE TITLE
Feature request: environmental variable or options to specify chromium's argument

### ISSUE THREAD

**Issue by atusy** [rstudio/chromote#20]
As discussed in #5,  chromote on docker requires `--no-sandbox` option.
Here, I want to notice that #5 may cause errors on packages depending on chromote.
For example, `webshot2::webshot` cannot specify `--no-sandbox`, and thus fails on docker.
I opened this issue here instead of webshot2 because I don't want individual packages to take care of this issue.

I'd appreciate if we can set chromium's options, including `--no-sandbox`, via environmental variable or options on R.

As a workaround, I made a following shell script and specified it to the `CHROMOTE_CHROMIUM` environmental variable.

```sh
#! /bin/sh
exec /usr/bin/chromium --no-sandbox --headless "$@"
```

**Comment by RLesur** [comment]
@atusy The `--no-sandbox` option is not required if you run the container with a dedicated seccomp profile, see <https://pagedown.rbind.io/#print-to-pdf-using-docker>.

**Comment by atusy** [comment]
@RLesur Thanks a lot for the tip!! Will try!!

**Comment by atusy** [comment]
It works perfectly! Thanks again!!
