### ISSUE TITLE
expose 10 second timeout as option 

### ISSUE THREAD

**Issue by dpastoor** [rstudio/chromote#22]
I know 10 seconds feels like a long time, but here is the issue we are currently facing:

On newly provisioned AMI's, chrome can take closer to 15-20 seconds to launch the first time the ami is run, hence we are continually running into the timeout error on https://github.com/rstudio/chromote/blob/master/R/chromote.R#L62

It would be great to expose this as an option (and I'd be happy to add as a PR), so for those of us sorry souls that have to wait that long the first time this doesn't force other workarounds.

```diff
 p <- promise_resolve(TRUE)$
          then(function(value) {
            promise_timeout(
              promise(function(resolve, reject) {
                private$ws$onOpen(resolve)
              }),
-              10,
+              getOption("chromote.websocket_timeout", 10),
              timeout_message = "Chromote: timed out waiting for WebSocket connection to browser."
            )
          })
```

**Comment by bschilder** [comment]
+1

**Comment by dpastoor** [comment]
Thank you!
