### ISSUE TITLE
chromote is not finding my chrome (Ubuntu 18.04)

### ISSUE THREAD

**Issue by bnicenboim** [rstudio/chromote#26]
I'm using Ubuntu 18.04 and I'm getting this error:

```
b <- ChromoteSession$new()
Error in find_chrome() : 
#  `google-chrome` and `chromium-browser` were not found. Try setting the CHROMOTE_CHROME environment variable or adding one of these executables to your PATH.
```
This is probably because it should be `chromium` in my system:

```
Sys.which("chromium")
#            chromium 
# "/snap/bin/chromium" 
```

**Comment by hadley** [comment]
Looks like this has since been fixed: https://github.com/rstudio/chromote/blob/e21c70c0e56a53563f7abe6072105fe0d10cf7f6/R/chrome.R#L123-L131
