### ISSUE TITLE
Incompatibility with github websocket

### ISSUE THREAD

**Issue by Skourtis** [rstudio/chromote#31]
When I try installing chromote with 

devtools::install_github("rstudio/chromote", dependencies = T)

I get this error
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'websocket' 1.1.0.9001 is being loaded, but >= 1.1.0.9002 is required

**Comment by wch** [comment]
Oops, fixed in fa68990.
