### ISSUE TITLE
Export `find_chrome` or implement `is_chrome_available`

### ISSUE THREAD

**Issue by atusy** [rstudio/chromote#33]
On github.com/yihui/knitr/pull/1918#discussion_r566879595, we discussed that it would be nice to implement `find_chrome` or implement `is_chrome_available`.
Then, other packages may check is chrome is available, and fallback to other methods when chrome  is unavailable.
We also think it would be nice if `find_chrome` is re-exported by **webshot2** so that we have a function similar to `webshot::find_phantomjs`.

cc. @cderv

**Comment by jhelvy** [comment]
Second this - in my [xaringanBuilder](https://github.com/jhelvy/xaringanBuilder) package I would like to be able to send better error messages if Chrome is missing, but I don't have a convenient way to do so right now.

**Comment by wch** [comment]
I've exported `find_chrome()` and increased the version to 0.0.0.9003.

**Comment by atusy** [comment]
Great! Thank you!!
