### ISSUE TITLE
Extract View Source

### ISSUE THREAD

**Issue by markwsac** [rstudio/chromote#35]
Thanks for this lovely package. Just wondering if it's possible to extract view source of the page. I tried finding this info in readme but couldn't get success.

**Comment by markwsac** [comment]
Got it. Thanks. Please find my code below -
```
  z <- b$Runtime$evaluate('document.documentElement.outerHTML')
  mydf <- z$result$value
```
Last question - can we use rvest on this? It seems it is not XML , hence not working.
`mydf %>% rvest::html_nodes("[id$='_hcontainer']")`

**Comment by cderv** [comment]
For reference, this has been also asked in **crrri**: https://github.com/RLesur/crrri/issues/105

Same solution should apply to **chromote**.
