### ISSUE TITLE
Inspector.enable not found 

### ISSUE THREAD

**Issue by markwsac** [rstudio/chromote#44]
`b <- ChromoteSession$new()` returns the below error.

**Error in onRejected(reason) : code: -32601
message: 'Inspector.enable' wasn't found**

 I checked on multiple versions of R. Same code works fine with prior version of chromote.

**Comment by wch** [comment]
Probably caused by #42.

@RLesur The `Inspector.enable` event is probably not available on all versions of Chrome, and I think the fix is to check for its existence before registering the handler.

**Comment by RLesur** [comment]
I'm so sorry for that: I forgot to test with the default `auto_events = TRUE`. Will do a PR to fix that!
