### ISSUE TITLE
screenshot() triggers error 

### ISSUE THREAD

**Issue by lodderig** [rstudio/chromote#46]
```

[1] "An error occurred: Error in onRejected(...): code: -32000\n  message: Cannot take screenshot with 0 height.\n"
Warning message:
In onRejected(reason) :
  An error occurred: Error in onRejected(...): code: -32000
  message: Cannot take screenshot with 0 height.
```

I am using Chromium on Ubuntu LTS 18.04.

While I am able to login and navigate the website (as I can see in Devtools viewport) both in the viewport or by using `b$Page$navigate`, I am unable to take a screenshot

```
library(chromote)
b <- ChromoteSession$new()
b$view()
b$Page$navigate("https://dev79379.service-now.com/nav_to.do?uri=%2Fcatalog_home.do%3Fsysparm_view%3Dcatalog_default")
b$screenshot()
```

After the `b$screenshot()` command, the viewport is frozen (interaction is not any longer possible)

Do I overlook something or is this a bug?

**Comment by wch** [comment]
The `screenshot()` method tries to size the viewport to the size of the content, but it is possible that it is not getting the correct dimensions.

https://github.com/rstudio/chromote/blob/4bce61c2606f5d52f9412afc953b7577f2965e66/R/screenshot.R#L71-L79

You could try calling `b$Page$captureScreenshot()` directly, but I believe this will only capture the portion in the viewport.

**Comment by lodderig** [comment]
thanks,

`image_data <-  b$Page$captureScreenshot()
 writeBin(jsonlite::base64_dec(image_data$data), "test.png")
 `
returns indeed the part visible in the viewport, what does this tell us?
(and what can I try to fix this ?)

where can a height 0 come from? Too slow rendering ?
