### ISSUE TITLE
Docker: Chrome debugging port not open after 10 seconds 

### ISSUE THREAD

**Issue by sneumann** [rstudio/chromote#5]
Hi, when running chromote inside a Debian docker container with chromium I get 
```
export CHROMOTE_CHROME=/usr/bin/chromium
...
> library(chromote)
> b <- ChromoteSession$new()
Error in launch_chrome(path, args) : 
  Chrome debugging port not open after 10 seconds.
```
I'd probably need a few hints how chromium is spawned and what interprocess communication (IPC) is used, to check whether those still work inside a container. 
Yours,
Steffen

**Comment by sneumann** [comment]
So, chromium does not like Docker: 
```
/usr/bin/chromium --headless --remote-debugging-port=0
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
```
and wants to be started as non-root user with 
`/usr/bin/chromium --no-sandbox --headless --remote-debugging-port=0`

Yours, Steffen

**Comment by wch** [comment]
I made an update to provide better startup error messages, and this is what I get when I run it in Docker:

```R
> ChromoteSession$new()
Error in launch_chrome(path, args) : 
  Failed to start chrome. Error: [0808/182701.557515:ERROR:zygote_host_impl_linux.cc(89)] Running asroot without --no-sandbox is not supported. Seehttps://crbug.com/638180.
```

**Comment by sneumann** [comment]
I probably just need an example how to pass args to 
https://github.com/rstudio/chromote/blob/1e9758aedc4ffeb7362d8ee9aeb3fe82b3fb57a1/R/chrome.R#L8
from high-level code like `webshot2`. Or write a small chromium-wrapper adding `--no-sandbox`  work-araound. Yours, STeffen

**Comment by wch** [comment]
I think you'll need to start Chrome with `--no-sandbox`. You can do it and use it for the default Chromote object with:

```R
set_default_chromote_object(
  Chromote$new(browser = Chrome$new(args = "--no-sandbox"))
)
```

Then you can create a `ChromoteSession` as normal. I believe webshot2 should also just work.

```R
ChromoteSession$new()
```

I don't want to make `--no-sandbox` the default, though it might be good to make it simpler to pass arguments to Chrome.

**Comment by sneumann** [comment]
Awesome, that worked. For the record, Dockerfile is https://github.com/sneumann/metaRbolomics/blob/master/connectivity/Dockerfile
and Rmd script is https://github.com/sneumann/metaRbolomics/blob/master/connectivity/revDepNet.Rmd
Yours, Steffen

**Comment by cderv** [comment]
@wch FWIW in `crrri` we had some arguments to activate some default options depending on where you want to use chrome headless. `--no-sandbox` is one of this arguments required in some case

* On windows, we have the `--no-sandbox` as default for `headless` (see [`crrri:::chr_windows_args()`](https://github.com/RLesur/crrri/blob/aeea7d6fd0bba7b40cc51ff160ed90f96ca2dee6/R/Chrome.R#L467)). I don't find out why we did that and if it is still required or not. (@Rlesur do you remember ?)
* On travis, `--no-sandbox` [is required](https://docs.travis-ci.com/user/chrome#sandboxing). So, for testing purposis, we add as default when on travis (see [`crrri:::chr_travis_args()](https://github.com/RLesur/crrri/blob/aeea7d6fd0bba7b40cc51ff160ed90f96ca2dee6
/R/Chrome.R#L483))`

So we did not made it a default _in all all case_. I don't know if this could be interesting in chromote to be able to activate some options this ways, through arguments. 

Also,  from https://developers.google.com/web/updates/2017/04/headless-chrome#faq
> Note: --no-sandbox is not needed if you [properly setup a user](https://github.com/GoogleChromeLabs/lighthousebot/blob/master/builder/Dockerfile#L35-L40) in the container. 
So configuring a user for chrome makes it possible to use it without the `--no-sandbox` flag. (if you can do that).

**Comment by RLesur** [comment]
> On windows, we have the `--no-sandbox` as default for `headless`

Of course, this comes from me (as in [`pagedown::chrome_print()`](https://github.com/rstudio/pagedown/blob/574beb49bf6393857f3c7563c3535d84ac1e8bbc/R/chrome.R#L69)). This was because I did not succeed to run headless Chrome on my pro computer without this option.
I agree with @wch: this is not recommended at all.

**Comment by cderv** [comment]
Thanks @RLesur. We may have to test it again. `chromote` works fine on my windows machine without specifing this option. 🤔

**Comment by RLesur** [comment]
FWIW, I've documented a better way to run Chromium in docker in the **pagedown** documentation: <https://pagedown.rbind.io/#print-to-pdf-using-docker>. 
The goal is to avoid the use of the `--no-sandbox` flag.

**Comment by sneumann** [comment]
... that involves to use `--security-opt seccomp="chrome.json"´ which is really cool! Thx, Steffen
