### ISSUE TITLE
Add function to install Chromium

### ISSUE THREAD

**Issue by wch** [rstudio/chromote#7]

**Comment by hafen** [comment]
+1 - A clean isolated Chromium would make for a better user experience. 

I wonder if [this](https://gitlab.com/hrbrmstr/decapitated/-/blob/master/R/download-chromium.R) from @hrbrmstr's decapitated package plus rappdirs would get close. Maybe Linux is trouble?

**Comment by PaulinCharliquart** [comment]
hi,

Best solution is to use [puppeteer](https://developer.chrome.com/blog/chrome-for-testing/#how-can-i-get-chrome-for-testing-binaries). Then define the chromote path:

```{R}
Sys.setenv("CHROMOTE_CHROME"="path_to/chrome-linux64/chrome")
```

regards,
Paulin

**Comment by hadley** [comment]
Closing in recognition that while this would be useful, it would be a lot of work and doesn't seem to be much of a problem for folks in practice.

**Comment by gadenbuie** [comment]
The introduction of a new headless mode in Chrome has elevated this from "not much of a problem" to "can very much be a problem". It's still a lot of work but is now worth reconsidering.
