### ISSUE TITLE
Rename / remove public R6 methods

### ISSUE THREAD

**Issue by schloerke** [rstudio/chromote#75]
`ChromoteSession`
* Remove `$get_parent()` or remove `$parent` field
  * Many examples already use `$parent`, but as a field, it can also be set. I believe this is wrong and should only keep `$get_parent()`.
* Move `self$protocol` to `private$protocol`
  * It is only used by EventManager which is created in the `ChromoteSession$initialize()` method. If `private` was sent in with `private$protocol` available, the field could be removed.
* Move `self$send_command()` to `private$send_command()`
  * It is only used by EventManager which is created in the `ChromoteSession$initialize()` method. If `private` was sent in with `private$protocol` available, the field could be removed.

`Chromote`
* Rename `$stop()` to `$close()`
  * For naming consistency. `ChromoteSession` uses `$close()`.
* I'd like to move `self$send_command()` to `private$send_command()`, but I do not see a clean way to achieve this.
  * Similar with `ChromoteSession$mark_closed()`, `ChromoteSession$init_promise()`, `ChromoteSession$get_auto_events()`, `ChromoteSession$invoke_event_callbacks()`

@wch, thoughts?

**Comment by wch** [comment]
You can lock `parent` with this in the initializer:

```
lockBinding("parent", self)
```
