### ISSUE TITLE
Chromote not working on windows 10

### ISSUE THREAD

**Issue by dickoa** [rstudio/chromote#77]
Hi @schloerke,

I hope all is good. Thanks for your work on this package.
I don't know what changed but I now have an issue when I do this on Windows 

```r
library(chromote)
Sys.getenv("CHROMOTE_CHROME")
## [1] "C:\\\\Program Files\\\\BraveSoftware\\\\Brave-Browser\\\\Application\\\\brave.exe"

b <- ChromoteSession$new()
b$view()
## [1] 127
## Warning message:
## In system(paste0("\"", browser, "\" ", if (encodeIfNeeded) URLencode(url) else url),  :
##   '""C:\\Program' not found
```

I was working fine couple of month ago. I only have this issue on windows, it's working well on Linux.
I suspect that it's related to the path and I think it's related to this 
https://github.com/rstudio/chromote/blob/03f8206add670400cb0f30bb3787172a6444ba24/R/utils.R#L85

Using just `browseURL` works, but since `get_path` is private, I can't use it for my test.

Can someone else can reproduce this error?

Thanks for the support,
Ahmadou

**Comment by schloerke** [comment]
TIL `browseURL()` quotes the browser path if provided!
