### ISSUE TITLE
Add support for taking screenshots of PDF files

### ISSUE THREAD

**Issue by wch** [rstudio/chromote#8]
Headless Chrome doesn't support PDFs for some reason, but the pdf.js library can be used to render PDFs. https://mozilla.github.io/pdf.js/examples/

It's possible this is outside the scope of Chromote, though.

**Comment by gadenbuie** [comment]
IIUC, this is now supported by Chrome DevTools Protocol and therefore by chromote (since it's being used by `webshot2::webshot()`.
