### ISSUE TITLE
Add an "Empty Cache and Hard Refresh" method?

### ISSUE THREAD

**Issue by yogat3ch** [rstudio/chromote#98]
When using `chromote` with `shinytest2` via a terminal R session, it appears that DOM Javascript and CSS dependencies are always loaded from the cache whenever possible, even when changes are present in the files. 
There does not appear to be a way to force a `chromote` session to drop the cache and hard reload such that the dependencies refresh. The dependencies are stuck in their initial state when the R session was loaded. The only way to get dependencies to refresh is to exit from the app, exit from the R session, reload the R session, and reload the app. 

An AppDriver method that drops the cache and hard reloads would be much easier!

**Comment by hadley** [comment]
You should be able to do something like:

```R
session$Network$clearBrowserCache()
session$Page$reload()
```

Or possibly just:

```R
session$Page$reload(ignoreCache = TRUE)
```

**Comment by yogat3ch** [comment]
Thanks for the tip @hadley! Is there a way to access the `session` environment from the `chromote` object? Or is this only accomplished by tying the code above to an `actionButton` / `observeEvent` within the app's code and have the `chromote` click the actionButton?

**Comment by hadley** [comment]
@yogat3ch I'm assuming you're already doing something like `session <- chromote::ChromoteSession$new()`.

**Comment by yogat3ch** [comment]
Ah, I had assumed the above were referring to some methods of the [shiny session object](https://shiny.posit.co/r/reference/shiny/latest/session.html) that I had not been aware of. I see what you mean now, thank you for the advice @hadley!
