### ISSUE TITLE
view() shows websockets disconnection

### ISSUE THREAD

**Issue by Ljupch0** [rstudio/chromote#99]
Hi, I am coming back to code that used to work.

Now when calling b$View() I immediately get
"Debugging connection was closed. Reason: WebSocket disconnected"

When I click reconnect devtools it immediately disconnects.

Is this some IT security thing?

![image001](https://user-images.githubusercontent.com/46574875/225687113-00d6fa07-18bf-41ef-99c5-cf460f110ee0.png)

**Comment by wch** [comment]
I think this is the same issue as https://github.com/rstudio/shinytest2/issues/331.

**Comment by gadenbuie** [comment]
I wonder if it's related to [recent changes to headless mode in Chrome](https://developer.chrome.com/articles/new-headless/)? IIUC, as of Chrome 112, headless mode now uses the same engine as headful mode where previously headless mode was a completely separate engine.

I don't know the full context but the timing is suspicious and the linked article mentions the live viewer explicitly, so it seems feasible that something might have changed in that area.

**Comment by wch** [comment]
It looks like this is due to a security change in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1422444#c5

One workaround is to add `--remote-allow-origins=*`, but I think that makes it too open. It would be better to use `--remote-allow-origins=http:127.0.0.1:xxxx`, where `xxxx` is the port number. However, the problem with that is that we currently don't set the port number -- we let Chrome choose it when we use the option `--remote-debugging-port=0`. So for a proper fix, we might need to randomly select a port in R, then pass that port number to Chrome when starting it up.

**Comment by wch** [comment]
I made a workaround for testing in #100. You can try it with:

```R
remotes::install_github("rstudio/chromote@origin-testfix")
```

**Comment by gadenbuie** [comment]
@wch Since chromote doesn't currently expose an option to set the port, should it internally find a random port? Or would you prefer to expose an argument for setting the port number?

**Comment by wch** [comment]
I think it makes sense to always find a random port. I can't think of a reason offhand why one would need a specific port number.

**Comment by edwardhealey** [comment]
hey @wch, I am still getting the same issue as #99 when I install the package via `remotes::install_github("rstudio/chromote")` and run
```
library(chromote)

chrome <- ChromoteSession$new()
chrome$view()
```

**Comment by wch** [comment]
@edwardhealey I just bumped the version number to 0.1.1.9001, so please reinstall, test it, and if it still fails, please include the output from `sessioninfo::session_info()`.

**Comment by zsigmas** [comment]
@edwardhealey For me it seemed that installing the fix provided by wch was not enough, but I needed to also update chromium for the $view to work again. I assume it was the update as in a given moment $view was working with google-chrome (installed after finding this problem to test if that solved the problem, so most recent version) but not in chromium (an undetermined older version).

**Comment by mjfrigaard** [comment]
# Chromium <> shinytest2 issue

Hi there, 
Not sure if this is the same issue, but I ran into a similar error while running tests in shinytest2 recently (and landed here when looking for a fix). 

1. I installed Chromium via [homebrew](https://formulae.brew.sh/cask/chromium)

``` r
==> Downloading https://download-chromium.appspot.com/dl/Mac?type=snapshots
==> Downloading from https://commondatastorage.googleapis.com/chromium-browser-s
######################################################################### 100.0%
Warning: No checksum defined for cask 'chromium', skipping verification.
==> Installing Cask chromium
==> Moving App 'Chromium.app' to '/Applications/Chromium.app'
==> Linking Binary 'chromium.wrapper.sh' to '/usr/local/bin/chromium'
🍺  chromium was successfully installed!
``` 

2. Located Chromium 

``` r
library(chromote)
chromote::find_chrome()
[1] "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
```

3. Created new session 

``` r
b <- ChromoteSession$new()
b$view()
```

Then I see the following: 

![719C36DF-9078-491A-8C29-2964EA00BC04](https://user-images.githubusercontent.com/8368326/235342590-f3df0555-e72b-4de1-85a1-bff2eb5f5413.png)


Also—the same issue arises in `shinytest2` when using app driver in console: 

1. With the following app folder (from [this example](https://www.youtube.com/watch?v=Gucwz865aqQ)):

```
├── app.R
├── greet.Rproj
└── tests
    ├── testthat
    │   ├── _snaps
    │   │   └── shinytest2
    │   │       ├── hello-barret-001.json
    │   │       └── hello-barret-001_.png
    │   ├── setup-shinytest2.R
    │   └── test-shinytest2.R
    └── testthat.R

5 directories, 7 files
```

And the contents of `test-shinytest2.R` containing:

``` r
library(shinytest2)

test_that("{shinytest2} recording: hello-barret", {
  app <- AppDriver$new(name = "hello-barret", height = 483, width = 862)
  app$set_inputs(name = "Barret")
  app$click("greet")
  app$expect_values()
})
```

When I attempt to run the following in the console, 

```r
app <- AppDriver$new(name = "hello-barret", height = 483, width = 862)
app$view()
```

![0E34A87D-E7DC-4507-AC57-9B4152441F00](https://user-images.githubusercontent.com/8368326/235342599-dd6dbd9d-e8da-4f44-9083-77648ebba3a4.png)

My apologies is this issue is redundant and addressed elsewhere! Thank you for your hard work on these amazing tools!

``` r
─ Session info ───────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.3 (2023-03-15)
 os       macOS Ventura 13.3.1
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Los_Angeles
 date     2023-04-30
 rstudio  2023.03.0+386 Cherry Blossom (desktop)
 pandoc   NA

─ Packages ───────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 backports     1.4.1   2021-12-13 [1] CRAN (R 4.2.0)
 brio          1.1.3   2021-11-30 [1] CRAN (R 4.2.0)
 callr         3.7.3   2022-11-02 [1] CRAN (R 4.2.0)
 checkmate     2.2.0   2023-04-27 [1] CRAN (R 4.2.3)
 chromote    * 0.1.1   2022-09-07 [1] CRAN (R 4.2.0)
 cli           3.6.1   2023-03-23 [1] CRAN (R 4.2.2)
 crayon        1.5.2   2022-09-29 [1] CRAN (R 4.2.0)
 digest        0.6.31  2022-12-11 [1] CRAN (R 4.2.0)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.2.0)
 fansi         1.0.4   2023-01-22 [1] CRAN (R 4.2.2)
 fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.2.0)
 fs            1.6.2   2023-04-25 [1] CRAN (R 4.2.3)
 glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
 htmltools     0.5.5   2023-03-23 [1] CRAN (R 4.2.2)
 httpuv        1.6.9   2023-02-14 [1] CRAN (R 4.2.2)
 httr          1.4.5   2023-02-24 [1] CRAN (R 4.2.0)
 jsonlite      1.8.4   2022-12-06 [1] CRAN (R 4.2.2)
 later         1.3.0   2021-08-18 [1] CRAN (R 4.2.0)
 lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.2.0)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
 mime          0.12    2021-09-28 [1] CRAN (R 4.2.0)
 pillar        1.9.0   2023-03-22 [1] CRAN (R 4.2.0)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.0)
 processx      3.8.1   2023-04-18 [1] CRAN (R 4.2.0)
 promises      1.2.0.1 2021-02-11 [1] CRAN (R 4.2.0)
 ps            1.7.5   2023-04-18 [1] CRAN (R 4.2.0)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.0)
 Rcpp          1.0.10  2023-01-22 [1] CRAN (R 4.2.0)
 rlang         1.1.1   2023-04-28 [1] CRAN (R 4.2.0)
 rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.0)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
 shiny         1.7.4   2022-12-15 [1] CRAN (R 4.2.0)
 shinytest2  * 0.2.1   2023-02-21 [1] CRAN (R 4.2.0)
 testthat    * 3.1.7   2023-03-12 [1] CRAN (R 4.2.0)
 tibble        3.2.1   2023-03-20 [1] CRAN (R 4.2.0)
 utf8          1.2.3   2023-01-31 [1] CRAN (R 4.2.2)
 vctrs         0.6.2   2023-04-19 [1] CRAN (R 4.2.0)
 websocket     1.4.1   2021-08-18 [1] CRAN (R 4.2.0)
 withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.0)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 4.2.0)

 [1] /Library/Frameworks/R.framework/Versions/4.2/Resources/library

─────────────────────────────────────────────────────────────────────────
```
